### ISSUE TITLE
SGM on OpenCV 

### ISSUE THREAD

**Issue by arrfou90** [dhernandez0/sgm#1]
Hello,  
I am trying to use your GPU SGM code on Jetson TX1 with  OpenCV4Tegra and CUDA 8, but I got the results as black images with unreasonable processing time around 0.1ms! Could you please tell me what configuration (i.e. OpenCV version, Cuda version, and the JetPacktx1 version) you used on Tigra x1/Jeston TX1?
However, SGM compiles and runs on PC with (GTX980, OpenCV 2 and Cuda 8.0) successfully.  
Thanks in Advance.

**Comment by dhernandez0** [comment]
This is usually an error related to the compute architecture used. Look at
the CMakeLists.txt and change the architecture to the one you are using,
please.

If you run the application with nvprof you will see that it does not run
any CUDA kernel.

2016-12-14 15:08 GMT+01:00 arrfou90 <notifications@github.com>:

**Comment by arrfou90** [comment]
Thank you very much.  That solved my problem with Jetson TX1. I have modified to the CMake file to consider the compute capability of Jetson TX1 "-gencode=arch=compute=53,code=sm_53"
