### ISSUE TITLE
Parameter setting on Kitti dataset

### ISSUE THREAD

**Issue by miketry0313** [dhernandez0/sgm#11]
Hi,

Thanks to share your code to the community!

I find out that your have tested the alg on Kitti dataset in the paper. Do you mind to share the parameters (e.x. p1, p2 value and the resized image size) you are using on Kitti?

Thanks a lot.

Mike

**Comment by dhernandez0** [comment]
Hi,

Because of code limitations, image width and height must be a divisible by 4, unfortunately, I can't remember how we cropped the image to cope with this restriction.

Regarding P1 and P2:
2 path: P1=7, P2=84
4 path: P1=7, P2=86
8 path: P1=6, P2=96
