### ISSUE TITLE
How to filter sky noise?

### ISSUE THREAD

**Issue by KeoChi** [dhernandez0/sgm#12]
Hello, I have a problem. There is so much sky noise(sky matching error), when I test the SGM in the open air. Did you find the situation? Do you know how to filter the sky noise(or detect the sky and then delete) on GPU?

**Comment by WASCHMASCHINE** [comment]
[2008 Detailed Real-Time Urban 3D Reconstruction from Video] mention the following way:
"We designed a simple module that learns the color distribution of the sky offline via k-means clustering and then suppresses pixels that are most likely sky from the final model" - no further details.

**Comment by ynma-hanvo** [comment]
i suspect uniqueness check, left-right consistent check will remove the noisy part for sky.
