### ISSUE TITLE
TX2 and 8 paths does not work

### ISSUE THREAD

**Issue by arnasIV** [dhernandez0/sgm#13]
Obviously, when you were building the software there was no TX2, so you did not prepare the code for it, but I am letting you know that there is an issue when 8 paths option is set:

> cudaDeviceSynchronize() returned unspecified launch failure(4) at disparity_method.cu:150

**Comment by dhernandez0** [comment]
Hi,

Thank you very much for your feedback, could you please provide more details about problem?
I'd be nice if you could upload the input data you're using so I can reproduce the error.

Thanks in advance

**Comment by arnasIV** [comment]
So, I a have Jetson TX2 board, with 3.1 JetPack. I would like to point out that there is no such problem with the Jetson TX1. And Jetson TX2 with PATH_AGGREGATION set to 4 works normally. I have noticed the issue only when using TX2 board(tried on several boards) and PATH_AGGREGATION = 8. 
util.h:

```
#define FERMI false
#define GPU_THREADS_PER_BLOCK_FERMI 256
#define GPU_THREADS_PER_BLOCK_MAXWELL 64

/* Defines related to GPU Architecture */
#if FERMI
  #define GPU_THREADS_PER_BLOCK   GPU_THREADS_PER_BLOCK_FERMI
#else
  #define GPU_THREADS_PER_BLOCK   GPU_THREADS_PER_BLOCK_MAXWELL
#endif
#define WARP_SIZE		32
```
configuration.h:

```
#define PATH_AGGREGATION 8
#define	MAX_DISPARITY 128
#define CENSUS_WIDTH 9
#define CENSUS_HEIGHT 7

#define OCCLUDED_PIXEL 128
#define MISMATCHED_PIXEL 129

#define TOP (CENSUS_HEIGHT-1)/2
#define LEFT (CENSUS_WIDTH-1)/2

typedef uint32_t cost_t;
#define MAX_COST 30

#define BLOCK_SIZE 256
#define COSTAGG_BLOCKSIZE GPU_THREADS_PER_BLOCK
#define COSTAGG_BLOCKSIZE_HORIZ GPU_THREADS_PER_BLOCK

#define ABS_THRESH 3.0
#define REL_THRESH 0.05

```


I am using images from Middlebury dataset. 
1. Resolution: 740x496 (divisible by 4)
Left:
![1](https://user-images.githubusercontent.com/24144845/33205752-c1209522-d110-11e7-911d-5e0a9f664c06.png)
Right
![2](https://user-images.githubusercontent.com/24144845/33205755-c4137d08-d110-11e7-9ca0-eb7f32ddfa89.png)
2. Resolution: 736x496 (divisible by 16)
Left:
![1r](https://user-images.githubusercontent.com/24144845/33207166-61039e50-d115-11e7-9e05-90ab81166d1d.png)
Right:
![2r](https://user-images.githubusercontent.com/24144845/33207179-65e41030-d115-11e7-85f1-020728ef5ed2.png)
3. Various resolutions: 640x480; 320x240..

**Comment by arrfou90** [comment]
Hello,
yes, this is true on TX2. In fact, it is not related to the whole diagonal paths but particularly to the kernel of the path UpDownLeftRight. If you comment the kernel of this path it should work. 
 
Arrfou

**Comment by dhernandez0** [comment]
Hi @arrfou90 and @arnasIV 

I think this is related to bug #16 that I just fixed thanks to @ankit1089sny

Could you please try this new version of the code? I think it should work properly now.

**Comment by dhernandez0** [comment]
No answer, so closing.
