### ISSUE TITLE
Disparity image looks very bad

### ISSUE THREAD

**Issue by mr-yamraj** [dhernandez0/sgm#14]
Hey,
I am using GTX 730 graphics card it has compute power of 3.0+.
I implemented the code with some changes so as to get it running(most of the errors were coming due to __restrict__ , and when I removed the __restrict it compiled and ran properly). But I didn't change any of the parameters.  I am attaching the output file. Please can you tell me what all parameters do I need to change. It looks like the image is fragmented in many pieces. I have used 2.png from the examples to make the disparity map.

This one is with 4 paths
![1](https://user-images.githubusercontent.com/17671208/33796066-36242088-dd13-11e7-9767-79cc4ba77c39.jpg)
This one is with 8 paths
![3](https://user-images.githubusercontent.com/17671208/33796069-410d00f0-dd13-11e7-8678-aa401d2be034.jpg)

**Comment by ShreyasSkandan** [comment]
Please share the changes that you made. The code works fine so it's most likely that one of the changes you made has caused this.

**Comment by dhernandez0** [comment]
Hi, 

As @ShreyasSkandan suggested, if you could upload your modifications and the images you're using I could try to reproduce your errors.

Thanks in advance

**Comment by dhernandez0** [comment]
No answer, so closing.
