### ISSUE TITLE
Same code different machines, different results

### ISSUE THREAD

**Issue by bigdimboom** [dhernandez0/sgm#15]
I have tested your code on two different machines. One is running on a Maxwell card, the other is running on a Pascal card. The one on Maxwell is running fine, the one on Pascal gives me bad disparity. Any idea why? Could you give me some guidelines to debug? i enclosed the bad one.
![image](https://user-images.githubusercontent.com/6119906/34697018-1f22e2c2-f49f-11e7-87f0-e79be3680c18.png)

**Comment by dhernandez0** [comment]
It's difficult to guess what is wrong, could you please send the images and parameters you're using? So that I can try to reproduce your problem.

**Comment by dhernandez0** [comment]
No answer, so closing.
