### ISSUE TITLE
Indexing bug at cost_aggregation.h:49

### ISSUE THREAD

**Issue by ankit1089sny** [dhernandez0/sgm#16]
@dhernandez0 
At cost_aggregation.h line 49, 
49    if(add_index > 0 && *col > cols) {
Sorry if I am wrong but shouldn't this be (*col > cols - 1)  or (*col >= cols)?
If it is the way it is right now, the value at col would reach W, whereas it should be from 0 to W-1.

**Comment by dhernandez0** [comment]
Thanks! you're totally right, I've pushed a new version that fixes this.

**Comment by ankit1089sny** [comment]
Thanks for the fix!
