### ISSUE TITLE
sgm in jetson tx2  

### ISSUE THREAD

**Issue by pras2020** [dhernandez0/sgm#17]
Hello All

i am new to jetson and cuda when i build the sgm code in jetson after executing  i am getting below error.
"Error: invalid device function 8"
will be really helpfull if some one suggest me were i am going wrong.

**Comment by pras2020** [comment]
the issue is solved

**Comment by jzyztzn** [comment]
@pras2020 I also had the same error，
`Error: invalid device function 8`
How did you solve it?

**Comment by smmmmi** [comment]
Error: invalid device function 8

This is related to the [Compute capability (version)](https://en.wikipedia.org/wiki/CUDA) of your GPU
To fix this problem in the cmake list file add these lines based on your GPU under the set CUDA_NVCC_FLAGS:

    -gencode=arch=compute_53,code=sm_53
    -gencode=arch=compute_60,code=sm_60
    -gencode=arch=compute_61,code=sm_61

... use same format and complete for higher GPUs,  sm_70 , sm_71 ...

then rebuild:
rm -r ./build
mkdir build
cmake ..
make
