### ISSUE TITLE
Disparity value 64 instead of 128 

### ISSUE THREAD

**Issue by pras2020** [dhernandez0/sgm#18]
Hello All

Is it possible to change the value from 128 to 64 for maximum disparity value. i saw a closed issue https://github.com/dhernandez0/sgm/issues/4
regarding disparity value and tried changing the uint32_t to uint16_t but not sure i am doing correctly. Can some one help me for changing maximum disparity value to 64.

**Comment by dhernandez0** [comment]
As I said in #4 it should be possible to change it, but apart from using uint16_t you should also modify some code as explained in #4. However, I do not have time to do this. In your case, you can actually just use it as it is, if your maximum disparity is 64, it should not make a huge difference (just maybe some wrong disparity estimations > 63).

**Comment by ynma-hanvo** [comment]
hi, dhernandez0.
but i also need max disparity to be 64 as my cost volume only have  64 depth due to speed . can you give some instructions how to change to 64. 

> As I said in #4 it should be possible to change it, but apart from using uint16_t you should also modify some code as explained in #4. However, I do not have time to do this. In your case, you can actually just use it as it is, if your maximum disparity is 64, it should not make a huge difference (just maybe some wrong disparity estimations > 63).
