### ISSUE TITLE
Black images with 2 neighbours

### ISSUE THREAD

**Issue by Leo-Mrl** [dhernandez0/sgm#2]
Hello,
I have been trying out this project on a Jetson TX1 with Cuda 8.0, and in most cases obtained great results and performances. However, when trying to compute the stereo matching with only 2 neighbours, the program returned completely black images.
This behavior is really strange considering that the algorithm runtime is actually of around 80fps when using this option, which is consistent with the expected performance.

Thank you very much, and I will remain available for any enquiry.

**Comment by dhernandez0** [comment]
Hello Leo,

Could you provide some sample images so I can reproduce the error?

Thanks!

**Comment by Leo-Mrl** [comment]
Hello Daniel,

![tsukuba_left](https://cloud.githubusercontent.com/assets/16349909/22419155/73c6a5c4-e6dc-11e6-842f-c35b2a6929d9.png)
![tsukuba_right](https://cloud.githubusercontent.com/assets/16349909/22419163/7914c5b0-e6dc-11e6-833e-74a77c27e472.png)

Merely using the Tsukuba sample from the Middlebury dataset produces a black image, and it does so with any input data when setting the number of neighbours to "2" in configuration.h.

**Comment by dhernandez0** [comment]
ok, I think you mean you set "PATH_AGGREGATION=2", am I correct?

This is currently not supported, the implementation only works with 4 and 8, anyway this would be an interesting extension, if you need this I can implement it, is that what you meant?

I will modify the README file to clarify only 4 and 8 are supported at the moment, sorry.

**Comment by dhernandez0** [comment]
actually this should be implemented but somehow it was removed, anyway the implementation is straightforward, so I will try to implement it this week.

**Comment by Leo-Mrl** [comment]
Oh ok that's why then, thank you very much for the info. If you have time for that, otherwise no need to hurry, I can also look into that myself.
Thank you very much again !
