### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by AntonBaburov** [dhernandez0/sgm#21]
Hello,
I am trying to use your SGM code, but I can't build it, because I get "undefined reference to" error. I use Ubuntu 16.04 LTS, OpenCV 3.3.1 (included in ROS), CMake 3.5.1, CUDA 8.0 and nVidia GTX 1080. After several hours of searching in google and trying to solve this error I still can't build your code. It seems that the problem is in OpenCV. I am newbie in Linux, CV and CUDA, so I need help.

Here my build log:

anton@smartcar:~/sgm/build$ cmake ..
- The C compiler identification is GNU 5.4.0
- The CXX compiler identification is GNU 5.4.0
- Check for working C compiler: /usr/bin/cc
- Check for working C compiler: /usr/bin/cc -- works
- Detecting C compiler ABI info
- Detecting C compiler ABI info - done
- Detecting C compile features
- Detecting C compile features - done
- Check for working CXX compiler: /usr/bin/c++
- Check for working CXX compiler: /usr/bin/c++ -- works
- Detecting CXX compiler ABI info
- Detecting CXX compiler ABI info - done
- Detecting CXX compile features
- Detecting CXX compile features - done
- Found OpenCV: /opt/ros/kinetic (found version "3.3.1") 
- Looking for pthread.h
- Looking for pthread.h - found
- Looking for pthread_create
- Looking for pthread_create - not found
- Looking for pthread_create in pthreads
- Looking for pthread_create in pthreads - not found
- Looking for pthread_create in pthread
- Looking for pthread_create in pthread - found
- Found Threads: TRUE  
- Found CUDA: /usr/local/cuda (found version "8.0") 
- Configuring done
- Generating done
- Build files have been written to: /home/anton/sgm/build

anton@smartcar:~/sgm/build$ make
[ 14%] Building NVCC (Device) object CMakeFiles/sgm.dir/sgm_generated_costs.cu.o
[ 28%] Building NVCC (Device) object CMakeFiles/sgm.dir/sgm_generated_main.cu.o
[ 42%] Building NVCC (Device) object CMakeFiles/sgm.dir/sgm_generated_median_filter.cu.o
[ 57%] Building NVCC (Device) object CMakeFiles/sgm.dir/sgm_generated_hamming_cost.cu.o
[ 71%] Building NVCC (Device) object CMakeFiles/sgm.dir/sgm_generated_disparity_method.cu.o
/home/anton/sgm/disparity_method.cu(40): warning: variable "d_L7" was declared but never referenced

/home/anton/sgm/disparity_method.cu(40): warning: variable "d_L7" was declared but never referenced

/home/anton/sgm/disparity_method.cu(40): warning: variable "d_L7" was declared but never referenced

/home/anton/sgm/disparity_method.cu(40): warning: variable "d_L7" was declared but never referenced

/home/anton/sgm/disparity_method.cu(40): warning: variable "d_L7" was declared but never referenced

[ 85%] Building NVCC (Device) object CMakeFiles/sgm.dir/sgm_generated_debug.cu.o
Scanning dependencies of target sgm
[100%] Linking CXX executable sgm
CMakeFiles/sgm.dir/sgm_generated_main.cu.o: In function `disparity_errors(cv::Mat, char const*, int*, int*)':
/home/anton/sgm/main.cu:54: undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
CMakeFiles/sgm.dir/sgm_generated_main.cu.o: In function `main':
/home/anton/sgm/main.cu:164: undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/home/anton/sgm/main.cu:169: undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/home/anton/sgm/main.cu:177: undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
/home/anton/sgm/main.cu:177: undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
/home/anton/sgm/main.cu:181: undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
/home/anton/sgm/main.cu:181: undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
/home/anton/sgm/main.cu:211: undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
/home/anton/sgm/main.cu:211: undefined reference to `cv::imwrite(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
/home/anton/sgm/main.cu:220: undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
/home/anton/sgm/main.cu:220: undefined reference to `cv::imwrite(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/sgm.dir/build.make:169: recipe for target 'sgm' failed
make[2]: *** [sgm] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sgm.dir/all' failed
make[1]: *** [CMakeFiles/sgm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Best regards, Anton.

**Comment by MPForte** [comment]
hello, I have exactly your same environment 
(Ubuntu 16.04 LTS, OpenCV 3.3.1 (included in ROS), CMake 3.5.1, CUDA 8.0 and nVidia GTX 1080).
Did you manage to make this code run?

**Comment by dhernandez0** [comment]
Looks like some problem with your opencv environment.
