### ISSUE TITLE
Some wrong with the processing speed

### ISSUE THREAD

**Issue by changqiong** [dhernandez0/sgm#22]
Hi,  Daniel Hernandez-Juarez
Thanks for your code.
It helps me a lot to understand the SGM.
I have run your code on Jeston TX2 smoothly.
But I have some trouble about the processing speed.
I changed the input images as 640*480, and got the processing speed as following:
4 path directions:   20fps                   
8 path directions:    9fps
All of them are about half of your results.
I don't know the reason of that. Maybe the Pascal architecture cannot runs your code very well?
If you know something about that, could you help me?
Thank you!

**Comment by dhernandez0** [comment]
Hi, 

Is it possible that the GPU is running in low performance settings? Check this out: http://elinux.org/Jetson/Performance

Also, check that the X server is not running.
