### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by TLzh** [dhernandez0/sgm#23]
When I run this code by "./sgm dir p1 p2", there is a error that is "Error: no kernel image is available for execution on the device 48". What happend when I run it? How can I solve this problem? Thank you!

**Comment by MMMHT** [comment]
Same problem to me,and I solved it by add  -gencode=arch=compute_61,code=sm_61  to CMakeList.txt ,the number 61 is the Compute Capability of GPU, Then recompile CmakeList. 
Hope this could help you .

**Comment by TLzh** [comment]
Duplicate of #

**Comment by TLzh** [comment]
Thank you! Because I run this project on Jetson TX2, so I add -gencode=arch=compure_62,code=sm_62 to CMakeList.txt and it works. You really help me with this problem.

**Comment by zhu-ty** [comment]
thanks again
