### ISSUE TITLE
How to set the value of P1 and P2?

### ISSUE THREAD

**Issue by jasonlinuxzhang** [dhernandez0/sgm#24]
Thank you for sharing your code and thesis. I am not using KITTI dataset. Can you tell me how to set the value of P1 and P2? I am looking forward to your reply。

**Comment by dhernandez0** [comment]
I used these parameters for the paper:

2 path directions: P1=7, P2=84
4 path directions: P1=7, P2=86
8 path directions: P1=6, P2=96

You should see for your problem what values work better.

**Comment by tensorbuffer** [comment]
@dhernandez0 I have a question regarding the p1 and p2 with respect to the number of path. I think the cost is a sum of each path, so when the number of path increases the sum also increases, so shouldn't 8path p1 > 4path p1 > 2path p1?
