### ISSUE TITLE
Type of disparity image

### ISSUE THREAD

**Issue by jasonlinuxzhang** [dhernandez0/sgm#25]
Hello, in the final results, disparity image type is eight, disparityis 0-127 ,so the distance of only 128 changes, in 0.6-1m range, reduce disparity1, distance add 1 cm, and in the range of 3 meters, disparity decrease 1, distance will add  10 cm. Is there a way to change the disparity image type to 16 bits?

**Comment by shelumielzhang** [comment]
I also need 16 bits disparity image.Have you solved it?

**Comment by jasonlinuxzhang** [comment]
几个月之前解决了，我是参考opencv中sgm的插值方法，具体的算法我忘了，时间太久了。

**Comment by dhernandez0** [comment]
You can try to do it yourself and contribute it, but I do not have time to implement this.
