### ISSUE TITLE
GpuMat input to compute results invalid output

### ISSUE THREAD

**Issue by ravi0103** [dhernandez0/sgm#26]
I am trying to change the compute function to work with cv::cuda::GpuMat directly instead of cv::Mat.

But i am having issues with the cudaMemcpyAsync
`CUDA_CHECK_RETURN(cudaMemcpyAsync(d_im0, left.ptr<uint8_t>(), sizeof(uint8_t)*size, cudaMemcpyDeviceToDevice, stream1));`

In the above code, "left" is a GpuMat. I have tried various methods to overcome this issue. But i was not successful.

Find the faulty image attached.

![aftermemcpyasync](https://user-images.githubusercontent.com/41575435/43073854-a9de9936-8e98-11e8-8a2d-df944467d175.jpg)

How to copy the GpuMat data to "d_im0" properly?

**PS:** Similar issue is discussed in [http://answers.opencv.org/question/167465/how-to-pass-an-already-stored-data-in-gpu-by-gpumat-to-a-kernel/](here). Kindly let us know if this could be the reason for issue and a work around.

**Comment by dhernandez0** [comment]
Hi @ravi0103 

Could you please provide some code and data so that I can reproduce the issue?

Thanks
