### ISSUE TITLE
How to get stable depth map

### ISSUE THREAD

**Issue by bohan-w** [dhernandez0/sgm#28]
Hey Hernandez, great CUDA code by the way, I am testing out your code with a stereo camera. I am saw a few of your result in your paper and in your video, which I find the disparity map are very smooth. By when I tested out with a camera, which is fixed down pointing towards a **static** scene, the depth map is a bit unstable especially in the far away area. Depth value of a few area is varying between 1 meter to 20 meter. I play with the p1 and p2 value but still cannot get very static depth map. Any suggestion from you? Thanks!

**Comment by jasonlinuxzhang** [comment]
jasonlinuxzhang/sgm_cuda
This is a CUDA version based on OpenCV sgm. The effect is the same as that of OpenCV sgm, and the speed block is three times faster.
