### ISSUE TITLE
Performance drops on Jetson TX1 and TX2

### ISSUE THREAD

**Issue by ivo-gilles** [dhernandez0/sgm#29]
We just dis some experiments on both Jetson TX1 and TX2 board, but the fps results were quite lower than expected. In fact, our records are:
- Jetson TX1: 13.4 fps
- Jetson TX2: 27 fps
We all set the maximum power mode for both versions and use CUDA 9, Ubuntu 16 to run the experiment.
So please check and help us to answer the problem here.

**Comment by npsharit** [comment]
I had a similar issue. Then I saw the example images are 1280x480, and the white paper that claims 42 fps on a Tegra X1 states using 640x480 images.

After running the jetson_clocks.sh to max the clock speeds, and cropping the example images to 640x480, I got 50+ fps on the Jetson TX2.

**Comment by ivo-gilles** [comment]
@npsharit Thank you for your answer. I have test the algorithm with the size 640x480 on Jetson TX2 with nvpmodel -m 0 and jetson_clocks, the result is quite impressing at 107~108 fps and ~50fps for Jetson TX1.

**Comment by USTfgaoaa** [comment]
@aquariusnk How you get 107~108 fps? I can only get 53 fps on TX2. Did you change some configuration parameters?
