### ISSUE TITLE
The disparity image looks worse than sgm in Opencv and Matlab

### ISSUE THREAD

**Issue by PpEeIi** [dhernandez0/sgm#30]
Here are the pictures I used, the left image, the right image, and the generated disparity image, P1 =6,P2 = 96.

**Comment by jasonlinuxzhang** [comment]
I also encountered the same problem before, the author's sgm effect is a little worse than opencv sgbm, so I wrote the cuda version according to the opencv sgbm, its effect is exactly the same as opencv sgbm, the speed is 3-4 times faster.
https://github.com/jasonlinuxzhang/sgbm_cuda

**Comment by yaobaishen** [comment]
@jasonlinuxzhang your demo really looks great! I have given a star to it ~
I have tested dhernandez's sgm for some while and AFAIK it's an excellent opensource sgm cuda implement so far. Have you compared with this sgm repo? thanks.

**Comment by jasonlinuxzhang** [comment]
@yaobaishen No, this is the code I wrote when doing binocular ranging. I didn't find the same demo with the opencv sgbm algorithm on the Internet, considering the effect and considering the speed. So I wrote a cuda version based on opencv sgbm.

**Comment by yaobaishen** [comment]
Go back to the original topic, @PpEeIi I suggest you to check your stereo calibration at first, if the intrinsics and extrinsics are not accurate, the left/right rectified image may misalignment in the horizontal direction.
