### ISSUE TITLE
help to understand "recompute" and use of rp0,rp1,rp2,rp3

### ISSUE THREAD

**Issue by imranlivt** [dhernandez0/sgm#31]
Hi dhernandez,
     It is so far the best GPU implementation I have found for SGM. good going. I am trying to implement SGM as one part of my project thesis. I have tried to understand your code and i have a few questions.
1. why this recompute is required in the first place. can't the LEFT-RIGHT be similar to UP_DOWN cost aggregation
2. In LEFT_RIGHT cost aggregation, recompute is ON and it is using rp0,rp1,rp2,rp3 registers. Can you explain how these are being used?
3. in cost_aggregaiton.h line num 106: else block is not being used at all.  

any help would be appreciated. thank you

**Comment by edawrd03** [comment]
hi imranlivt, I've encountered same problems as you, got any answers?  @imranlivt @dhernandez0
