### ISSUE TITLE
Low FPS with visual studio 2019

### ISSUE THREAD

**Issue by tonifds** [dhernandez0/sgm#34]
it reaches 7 FPS with RTX 2080 Super , visual studio 2019, windows 10 and Core i9-9900K.

Any suggestions?

**Comment by dhernandez0** [comment]
Sorry, no idea why this is so slow. Could you check if it's using some kind of debug mode?

**Comment by bill2239** [comment]
Could you share how you compile in visual studio? Did you use cmake? Do you have to make any modification to make it work? Any help would be appreciated!
