### ISSUE TITLE
Error: no kernel image is available for execution on the device 209

### ISSUE THREAD

**Issue by Lightang6** [dhernandez0/sgm#35]
I have tried several different versions of CUDA , 8.0    9.0   10.1 ,   but it doesn't work

**Comment by bill2239** [comment]
I had the same issue. Have you found the solution?

**Comment by alexjunholee** [comment]
In CMakeLists.txt:23, you may set a proper option for CUDA_NVCC_FLAGS.

For example, add 
    -gencode=arch=compute_61,code=sm_61
for GTX1080, or
    -gencode=arch=compute_75,code=sm_75
for RTX2080.

**Comment by dhernandez0** [comment]
As @alexjunholee said, please make sure you're modifying CMakeLists.txt for your CUDA architecture. If the issue was different, please let me know.
