### ISSUE TITLE
"shadow" appears on disparity result

### ISSUE THREAD

**Issue by michaelnguyen11** [dhernandez0/sgm#37]
Dear @dhernandez0 ,

Thank you very much for the awesome SGM algorithms on GPU.

I'm testing your repository and the results look very good.
However there is a shadow appears on disparity results. Configuration : PATH_AGGREGATION = 8

![Screenshot from 2021-03-07 11-08-38](https://user-images.githubusercontent.com/32232707/110273942-46233580-8000-11eb-9c93-acecec6ef8a2.png)

I used Kalibr for the calibration step, tested with OpenCV's SGBM and got good results.

How do you think about this results ? Could you guide me how to overcome this issue ?

Many thanks in advance.

Best regards,
Hiep

**Comment by dhernandez0** [comment]
What is the maximum disparity used for OpenCV's SGBM? My implementation is limited to 128 max disparity, that might be the issue? Also, have you tried with PATH_AGGREGATION = 4?
