### ISSUE TITLE
Compile at TK1 jetson

### ISSUE THREAD

**Issue by sounansu** [dhernandez0/sgm#6]
I tried to compile on my TK1 jetson.
But some errors were occurred.

```

/home/ubuntu/SOUNANSU/sgm/util.h(142):` error: asm operand type size(4) does not match type/size implied by constraint 'l'

/home/ubuntu/SOUNANSU/sgm/util.h(148):` error: asm operand type size(4) does not match type/size implied by constraint 'l'

/home/ubuntu/SOUNANSU/sgm/util.h(157):` error: asm operand type size(4) does not match type/size implied by constraint 'l'

```

So, I changed util.h as blow,

```

diff --git a/util.h b/util.h
index 1b0a76c..f4dc940 100644
--- a/util.h
+++ b/util.h
@@ -139,22 +139,22 @@ __inline__ __device__ int shfl_xor_32(int scalarValue, const int n) {

 __device__ __forceinline__ uint32_t ld_gbl_ca(const __restrict__ uint32_t *addr) {
        uint32_t return_value;
-       asm("ld.global.ca.u32 %0, [%1];" : "=r"(return_value) : "l"(addr));
+       asm("ld.global.ca.u32 %0, [%1];" : "=r"(return_value) : "r"(addr));
        return return_value;
 }

 __device__ __forceinline__ uint32_t ld_gbl_cs(const __restrict__ uint32_t *addr) {
        uint32_t return_value;
-       asm("ld.global.cs.u32 %0, [%1];" : "=r"(return_value) : "l"(addr));
+       asm("ld.global.cs.u32 %0, [%1];" : "=r"(return_value) : "r"(addr));
        return return_value;
 }

 __device__ __forceinline__ void st_gbl_wt(const __restrict__ uint32_t *addr, const uint32_t value) {
-       asm("st.global.wt.u32 [%0], %1;" :: "l"(addr), "r"(value));
+       asm("st.global.wt.u32 [%0], %1;" :: "r"(addr), "r"(value));
 }

 __device__ __forceinline__ void st_gbl_cs(const __restrict__ uint32_t *addr, const uint32_t value) {
-       asm("st.global.cs.u32 [%0], %1;" :: "l"(addr), "r"(value));
+       asm("st.global.cs.u32 [%0], %1;" :: "r"(addr), "r"(value));
 }

 __device__ __forceinline__ uint32_t gpu_get_sm_idx(){

```
Are there crrect?

**Comment by dhernandez0** [comment]
that is correct

**Comment by jimcha21** [comment]
Hey @sounansu , did it worked properly on your TK1 ? I tried to build it with `-gencode arch=compute_32,code=sm_32` , as TK1 supports, but I didn't managed to make it work (black image result). Maybe my CMakeLists.txt is missing something about importing CUDA.
Also, @dhernandez0 I would be glad if you have any suggestion about my issue... : )

**Comment by dhernandez0** [comment]
Hi @jimcha21 
You should change -gencode arch=compute_32,code=sm_32 to the particular architecture of your machine. I think 32 is ok in your case, remove the rest of gencodes and if nothing works try: "nvprof ./sgm ..." to see if kernels are executed.

**Comment by jimcha21** [comment]
Hello @dhernandez0 , as I checked with `nvprof` my TK1's memory is almost full before executing the `CenterSymmetricCensusKernelSM2` kernel (1835.4/1892.4 MB occupied / ~ 57 MB only free), so it doesn't run it at all. Also, `nvprof`  refers it as a warning,

`==7660== Warning: Found 1 invalid records in the result.`
`==7660== Warning: This can happen if device ran out of memory or if a device kernel was stopped due to an assertion.`

and the kernel execution isn't mentioned anywhere in the `nvprof` `'profiling results'`. So I am guessing that this is the problem.. Do you have any suggestion? maybe to reduce the memory consumption ?

Thanks in advance, Mr @dhernandez0
Dimitris

**Comment by dhernandez0** [comment]
You can use lower resolution images so that it has enough memory.
