### ISSUE TITLE
How to generated both left and right disparity map in order to execute consistency check?

### ISSUE THREAD

**Issue by Baoxue1008** [dhernandez0/sgm#7]
Hello,
Your implement has excellent performance in terms of speed. However,the disparity map which is generated by your project has some noise. Is there any way to generate both left and right disparity map in order to execute consistency check?
Thanks
Bao

**Comment by arrfou90** [comment]
Hi, 
the idea I would follow to do left-right consistency check is as suggested in the original paper of SGM by Hirschmüller is to generate the disparity with respect to the right image also.  So you need to generate two disparity images and then apply the consistency check. At the implementation level you can just    naively  do it by exchanging parameters (d_transform0, d_transform1) inside the HammingDistanceCostKernel function. Thus, you get Disparity wrt left and to right images. 
Regards
Arrfou

**Comment by dhernandez0** [comment]
Yes, arrfou90 is right, you can do that and then if I am not wrong, you should change somewhere: x-d -> x+d. Because you should check MAX_DIS to the right in this case.

**Comment by yaobaishen** [comment]
I am trying to generate the right disparity map, as @arrfou90 said, exchange the d_transform0 and d_transform1 could run successfully, but the disparity quality is very poor, I think I need to change more code per @dhernandez0 's last comment. Could anybody give more hints how to do this? thanks.
