### ISSUE TITLE
Diparity layers 

### ISSUE THREAD

**Issue by arrfou90** [dhernandez0/sgm#8]
Hi,
I've used the algorithm and got really good results but once I've reprojected the 2D points to 3D by using the calculated disparity values with the following result  [point-cloud](http://i.stack.imgur.com/xS7SE.jpg) Where at the end of SGM implementation we have an array with aggregated costs for each pixel. The disparity is equivalent to the index with the lowest cost value. I think this results in individually layers in the point-cloud, i.e round surfaces are cut into many layers (see example [point-cloud](http://i.stack.imgur.com/xS7SE.jpg)).
 Please anyone have an idea what is the reason to have such layers which in my case (my stereo vision setups) are distant by 5mm?

Thank you for your help!
Arrfou

**Comment by dhernandez0** [comment]
Hi Arrfou,
I don't know if I understand what you mean by round surfaces. But I guess you refer to the brown face. 

Stereo vision measurement is discretized by parallel planes (0..127 for example), actually, the planes are not distant in a constant way, distances from plane (dis=127) and plane (dis=126) should be small ((baseline*focal)/127)-(baseline*focal)/126)). Distance for planes 1 and 2 should be bigger ((baseline*focal)/2)-(baseline*focal)/1)).

If you want to improve this, have a look at subpixel techniques.

**Comment by arrfou90** [comment]
Yep! This is absolutely true.
I gave the 5mm number just  to imply the least depth resolution I can get with my stereo setups. And yes, I meant by round faces like the brown face. Sub-pixel techniques ( e.g. polynomial interpolation are the key to have a continuous representation of surfaces ).
I am starting to do a polynomial interpolation implementation. I think that I can describe the subpixel interpolation as: 
    input: An array of values, representing a fitting function (e.g. polynomial).
    output: The lowest point of the fitting function.

I don't have a clear idea at the moment on how to do this (at the implementation level) as an improvement of your implementation. I think that I need to fit a polynomial for the aggregated costs of each pixel.

thanks in advance for any suggestions.

**Comment by dhernandez0** [comment]
Hi arrfou90,

The implementation could be a bit tricky: the final cost cube aggregation is performed while computing the last cube (last direction). Take a look at function "CostAggregationGenericIteration", when join_dispcomputation=true.

For example, if 4 directions are computed, the first 3 are computed and their cost cubes are saved in memory. The last one, is computed and reads the previous 3 cubes to add them and compute the minimum and saves the disparity image. This strategy is used to save memory bandwidth as this algorithm is bandwidth-limited. 

I think it is possible to implement subpixel estimation inside this function when join_dispcomputation=true.

**Comment by dhernandez0** [comment]
I'm closing this issue, but if you have any further question don't hesitate to ask.
