### ISSUE TITLE
Understanding d_cost arrangement in memory

### ISSUE THREAD

**Issue by ShreyasSkandan** [dhernandez0/sgm#9]
Hi Mr Hernandez,

First, I just wanted to say great job with this repository. It's one of the best implementations of CUDA accelerated SGM I've come across. Thank you very much for this!

I'm trying to dig into this code and implement some extra functionality off this code. I've been struggling trying to understand the representation of the d_cost volume.

I'm working with an image of width=960, height=800, disparity_levels=128. Therefore the volume of d_cost is 800*960*128=98304000 which makes sense. However, I'm not sure I understand the way the elements are arranged in this data structure. Is the volume arranged in row->column->disparity order?

i.e,
If i wanted to find the cost associated with co-ordinate location (row=2,column=1,disparity_level=0),
would this global memory indexing scheme hold true?
total_columns = 960;
MAX_DISPARITY=128;
index = d_cost[row x total_columns+column+(total_rows x total_columns) x disparity_level]
index = d_cost[2 x 960+1+(800 x 960) x 0]
index = d_cost[1921]

And with this assumption, the same 2D co-ordinate location in the next disparity level would lie in index location d_cost[2 x 960+1+(800 x 960) x 1] = d_cost[768000+1921] = d_cost[769921]?

I tried using this method arrangement and the results don't seem to make sense. I would greatly appreciate any input regarding the way the d_cost data-structure is laid out in memory.

This isn't an issue regarding the code repository, so I understand if you wish to close this issue immediately.

Thanks in advance,
Shreyas

**Comment by dhernandez0** [comment]
Hi Shreyas,

Sorry for the delay and thank you for your interest in my work :)

The order is row->column->disparity as you said. However, your example is wrong:

index = d_cost[**row** x total_columns x max_dis + **column** x max_dis + **disparity_level**]

If you have any other question regarding ordering you can reopen this bug.

**Comment by ShreyasSkandan** [comment]
Thank you very much Mr Hernandez, my tests work correctly now!
